name: Application CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    uses: org/TestGithubMavenBuildWorkflow/.github/workflows/maven.yml@v1
    with:
      java-version: "17"
      maven-args: "-B clean package"
      upload-artifact: true
    secrets:
      MAVEN_USERNAME: ''
      MAVEN_PASSWORD: ''
